export const actionTypes: {
  GET_SELECT_COIN_DETAILS: string;
  GET_SELECT_COIN_DETAILS_SUCCESS: string;
} = {
  GET_SELECT_COIN_DETAILS: 'GET_SELECT_COIN_DETAILS',
  GET_SELECT_COIN_DETAILS_SUCCESS: 'GET_SELECT_COIN_DETAILS_SUCCESS',
};
